MM-28861 Add endpoint to marketplace to retrive all versions of specified plugin.
mattermost/mattermost-marketplace pull request #142
Opened 2020-11-16 23:28 UTC by crspeller

#### Summary
Adds the endpoint `/api/v1/plugin/{id}` to retrieve all the version of a specified plugin. Will still follow all filter rules except the text filter. 
Needed for server PR to give feature flags the ability to install specific versions of plugins.

2020-11-17 10:53 UTC, hanzei approved these changes
The code looks good to me. One thought below:

I'm wondering if `GetPlugin` should behave the same way as `GetPlugins` and return only the latest version. To accomplish the behaviour you want, we would add a new field `IncludePrevious` (0/5 on the same) into `PluginFilter` that would then return also older version. That way both `GetPlugins` and `GetPlugin` would support getting only the latest version and all versions.

2020-11-17 15:13 UTC, lieut-data requested changes
Changes makes sense, but I do share @hanzei's sentiment about the significant semantic differences between `/plugins` and `/plugin`. For better or worse, the semantics-to-date have been "one version per plugin" returned, and there's a certain elegance to preserving that given the longevity of this service.

I do like @hanzei's suggestion of a flag to change the behaviour here (maybe `ReturnAllVersions`?). If we added `PluginId` as another flag, we could even just keep the current endpoint and be able to use the new `ReturnAllVersions` to dump everything if so desired. Open to suggestions here, though!

2020-11-17 15:13 UTC, lieut-data commented on internal/api/client.go
> +func (c *Client) GetPlugin(request *GetPluginsRequest, pluginid string) ([]*model.Plugin, error) {
nit: `pluginId`?

2020-11-17 15:13 UTC, lieut-data commented on internal/store/static.go
> +// GetPlugin retrieves all known version of a specific plugin compatable with the plugin filter given.
```suggestion
// GetPlugin retrieves all known versions of a specific plugin compatible with the given plugin filter.
```

2020-11-17 15:13 UTC, lieut-data commented on internal/store/static.go
> +
nit: spurious extra line

2020-11-17 15:13 UTC, lieut-data commented on internal/store/static.go
> +	// Sort the final slice by plugin name, ascending
```suggestion
	// Sort the final slice by plugin version ascending, then plugin name ascending.
```

2020-11-18 15:51 UTC, crspeller commented
Sorry for the force push. Had to because of the strange branches. To properly test I had to rebase on to the production branch but then back to this one.

2020-11-18 16:21 UTC, lieut-data approved these changes

2020-11-18 16:21 UTC, lieut-data commented
One endpoint to rule them all!

2020-11-19 16:17 UTC, merged