Fix GH action workflow for notifying incoming webhooks on community/hub servers
mattermost/mattermost-marketplace pull request #440
Opened 2024-05-17 16:01 UTC by mickmister

#### Summary

This PR uses newly set environment variables with incoming webhooks to send release updates to the community/hub servers.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/CLD-7673

https://hub.mattermost.com/private-core/pl/cdque38knirqpet1soc8x1398e

2024-06-24 10:22 UTC, hanzei approved these changes
Thanks for the fix :+1:

2024-07-04 08:40 UTC, hanzei commented on .github/workflows/notify-mm-blog.yml
>          uses: mattermost/action-mattermost-notify@master
Should we pin the version?

2024-07-04 08:42 UTC, hanzei requested changes
Let's merge https://github.com/mattermost/mattermost-marketplace/pull/441 first

2024-07-10 02:20 UTC, mickmister commented
Closing @hanzei

2024-07-10 02:20 UTC, closed without merging